Repository VerifiedInc/core-types, pull requests merged in 2024-01, with the labels that each got.

#56 [Actions] publich create typedoc step added.
  .github/workflows/publish.yaml
Labels: hotfix, 1 min review, single-line

#57 chore: add redirectUrl
  src/types.ts
Labels: 1 min review, single-line

#58 chore: add primary color to brand
  src/types.ts
Labels: 1 min review, single-line

#60 chore: add missing fields
  src/types.ts
Labels: hotfix, 1 min review

#61 chore: add isOneClick field
  src/types.ts
Labels: 1 min review, single-line

#62 chore: add presentation options variant of one-click
  src/types.ts
Labels: hotfix, 1 min review
